version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: x9474h7mPwSxAEZt92Nb
      MYSQL_DATABASE: testdb
      TZ: Europe/Paris
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - back-db

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: x9474h7mPwSxAEZt92Nb
    networks:
      - back-db

  back:
    depends_on:
      - db
    build: ./back/
    ports:
      - "8081:8081"
    restart: always
    networks:
      - back-db

  front:
    depends_on:
      - back
    build: ./front/
    ports:
      - "3001:3000"
    restart: always
    networks:
      - front-back

volumes:
  db_data:

networks:
  back-db:
  front-back: