- name: UpdateDeployment projet (front + back) version ARM
  hosts: VM
  become: true
  become_method: sudo

  tasks:
    - name: Mise à jour du cache APT
      apt:
        update_cache: yes

    - name: Stop and remove container back
      become: true
      shell: sudo docker stop t-yep-600-mar-6-1-finalproject-mateosalvy-back-1 && sudo docker rm t-yep-600-mar-6-1-finalproject-mateosalvy-back-1

    - name: Stop and remove container front
      become: true
      shell: sudo docker stop t-yep-600-mar-6-1-finalproject-mateosalvy-front-1 && sudo docker rm t-yep-600-mar-6-1-finalproject-mateosalvy-front-1

    - name: Delete image back
      become: true
      shell: sudo docker rmi t-yep-600-mar-6-1-finalproject-mateosalvy-back

    - name: Delete image front
      become: true
      shell: sudo docker rmi t-yep-600-mar-6-1-finalproject-mateosalvy-front

    - name: Delete volume front
      become: true
      shell: docker volume rm t-yep-600-mar-6-1-finalproject-mateosalvy_front-files

    - name: git pull & lancement docker-compose
      become: true
      shell: cd T-YEP-600-MAR-6-1-finalproject-mateo.salvy && git pull && docker-compose up -d
